# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://fandean.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Fan's Blog
#description: "A gem-based responsive simple texture styled Jekyll theme." # A mechanical dog。
description: "A mechanical dog."
keywords: 'Android,Linux,Java,Git,vim,jekyll'
author:
  name: fan
  job_title: 
  location: Shenzhen
  email: ccfan.dev@gmail.com
  social_links:
    - name: github
      url: https://github.com/fandean
    - name: stackoverflow
      url: https://stackoverflow.com/users/8247923/fan
#    - name: facebook
#      url:
#    - name: twitter
#      url: 
#    - name: vk
#      url:
#    - name: instagram
#      url:
#    - name: linkedin
#      url:
home:
  section1: <h1>Fan</h1>
  section2: <h2>A gem-based responsive simple texture styled Jekyll theme</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/fandean" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License
  cc_license_image: /assets/images/theme/cc-by-sa.png # Choose one at https://creativecommons.org/choose/
#  footer_content: A gem-based responsive simple texture styled Jekyll theme.  # "A mechanical dog."
 footer_content: "A mechanical dog."

#disqus:
#  shortname: fandean
#  public_key: SqM3TGVGvUM6YB1GRLHE7j5VHN6bjcls9BFqdrcY7ks9yippJEUsNtHuVY8fm6fu
#  id: fandean
# google_analytics: UA-102167099-2 # fandean.github.io
# google_analytics: UA-102167099-1 # faner.gitlab.io
# addthis_public_id: ra-595fc12cbd5b5125  # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
